# Generated by Django 5.1.7 on 2025-03-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_title', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('beds', models.IntegerField()),
                ('bath', models.FloatField()),
                ('property_sqft', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
